### ISSUE TITLE
【フィードバック】 Nix入門: ハンズオン編

### ISSUE THREAD

**Issue by ultimatile** [asa1984/nix-zenn-articles#14]
## Chapter 05 §1. Nix言語の基本

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-01-nix-lang-basics.md?plain=1#L108

変数定義のやり方を書かずに変数埋め込みの話があって混乱しました．
また，このコメントアウトを外せばそのまま動くのかと思ったら動かなかったので，後で函数評価に括弧がいるという話が出てきて混乱するので括弧は必要ないならない方が良いのではないでしょうか？
コメントで書かずに動く形で変数を定義してしまった方がわかりやすいと思います．
Nix言語初心者なので勘違いしてたらすみません．

---

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-01-nix-lang-basics.md?plain=1#L170-L171

この部分に函数定義が書いていないのは意図通りですか？
書き忘れているのか他所で定義した体なのか判断つかなかったので質問させてもらいました．
個人的には函数定義のやり方も書いてあったらうれしいと思いました．

---

あとZenn bookのchapterとAsahiさんのchapter/section番号があってややややこしいのですが，これはどうにもならないんでしたっけ．．．？

---

(感想)待望のハンズオン編ありがたいです．

**Comment by ultimatile** [comment]
読み進めたら下の方に変数定義も函数定義もいますね．．．

**Comment by asa1984** [comment]
1. 変数・関数定義について
変数・関数のあたりは意図通りで、データ型の話を一通り終えた後に変数・関数定義の話に入りたかったのでこのような書き方をしたのですが、仰る通り読者を混乱させかねないですね。そのままREPLに貼り付けても動く形に変更しようと思います。

---

2. Chapter/Sectionついて
Nix言語関連のトピック、Nix言語の実践的利用のトピック…という風に大域的な区分けをしたかったのですが、Zenn bookはchapterを階層化できないので独自の番号の振り方になってしまいました。ここは正直譲れない部分なので、「chapter」→「部」としてZennと重複しない表現に変えて対処します。

**Comment by ultimatile** [comment]
返信ありがとうございます．良いと思います．
また続きを読み進めて何かあれば報告させていただきたいのですが，このままこのissueに追加するのと，このissueは閉じて適宜issueを建てるのとどちらが良いでしょうか？

**Comment by asa1984** [comment]
前者の方が私もやりやすいので、閉じずに追加する方針でお願いします。助かります🙏

**Comment by ultimatile** [comment]
## Chapter 05 §1. Nix言語の基本

ほぼただの質問なのですが，inheritの説明だけ読むと糖衣構文にしか見えず，あまり必要性が感じられなかったのですが，inheritが構文として必要な理由はあるのでしょうか？

## Chapter 06 §2. 組み込み関数

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-02-builtins.md?plain=1#L24

タイポ：`mian.nix`→`main.nix` (そもそもこの`touch`のcodeいらないような...)

---

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-01-nix-lang-basics.md?plain=1#L515

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-02-builtins.md?plain=1#L64

`1.4. Nix言語とderivation`など他にもたくさんありますがChapterの参照はhyperlinkにした方が便利だと思います．

本日分（？）です🙇‍♂️．

**Comment by asa1984** [comment]
タイポ報告ありがとうございます。以下、質問・提案について…

## 1. inherit構文
仰る通りただの糖衣構文です。JavaScriptやRustで`{ x: x }`を`{ x }`と記述できるのと役割的には同じで、手間を減らすだけのものですね。言語機能として必要かどうかは測りかねますが、頻出の構文であり、少なくとも他人のNix式を読むには必要なので載せています。

## 2. ハイパーリンク
すみません、サボっていました😖
記事公開後に振られるであろうURLを入れておきます（プレビューサイトの方でもチャプター間リンクが機能するようURL変換処理を加えておきます）。

**Comment by ultimatile** [comment]
修正ありがとうございます．
inheritの質問に関しても答えていただきありがとうございました．
本日分です🙇．

## Chapter 07 §3. Flakeを作る
https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-03-flakes.md?plain=1#L186
タイポ：`作成しましがた`→`作成しましたが`

---

https://github.com/asa1984/nix-zenn-articles/blob/abc036f0225aadced99e7b8e70d444391a0c4b7a/books/nix-hands-on/ch01-03-flakes.md?plain=1#L190

ここでNixpkgsが何かということについて，「Nix入門」で扱ったからだと思いますが説明がなかったので，「Nix入門」にある

> [Nixpkgs](https://github.com/NixOS/nixpkgs)はNixの公式パッケージリポジトリです

のような一言説明が欲しいと思いました．

また，Chapter 12 「§2. Nixpkgsを使う」があるようなので「後ほどChapter 12でNixpkgsを用いた例を扱います」のような誘導があっても良いのかなと思いました．

関連して順番的に先取りになりますが，Chapter 12 「§2. Nixpkgsを使う」でもNixpkgsの説明は特にないので，ここで「詳しくは「Nix入門」の[Chapter 10　「Nixpkgs」](https://zenn.dev/asa1984/books/nix-introduction/viewer/10-nixpkgs)で」のように参照すると親切だと思いました．

## hyperlinkに関して

同一Book内へのhyperlinkですが，[他の方のZenn Bookの使い方](https://github.com/yo-goto/zenn-public-repo/blob/0958c5fd569fc28973d8f25970bbff78ebc6beb9/books/js-async-promise-chain-event-loop/1-epasync-begin.md?plain=1#L61)を見る限り，公開後に使用されるfullのaddressを書かなくても該当chapterのmarkdown file名(拡張子なし)だけ書いておけば良いようです．

言及した箇所だと

```
[1.4. Nix言語とderivation](ch01-04-derivation)
```

ですね．
自分でもちょっと試してみましたが，localのZenn CLI previewerだと死にますがZenn website上のviewerだと問題なさそうでした．

**Comment by asa1984** [comment]
なんと！完全なアドレスを指定せずともchapter間リンクを貼れるのは初めて知りました。検証までしていただき、ありがとうございます。

Nixpkgsについては、ご指摘のページの双方に補足を追加します。

**Comment by asa1984** [comment]
ハイパーリンクについてですが、chapterの識別子を指定するだけでジャンプできるのはZennの機能ではなく、HTMLのアンカー要素の相対URLとしての挙動でした（私の専門領域はWebフロントエンドなのに知らないなんて！😖）。
Zenn CLIのプレビューではURLにchapterの`.md`拡張子が含まれてしまうため機能しないようです。

**Comment by ultimatile** [comment]
対応お疲れ様です．
本日分です．
よろしくお願いします🙇．

## Chapter 07 §3. Flakeを作る

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch01-03-flakes.md?plain=1#L86

タイポ：`fleke`→`flake`

## Chapter 08 §4. Nix言語とderivation

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch01-04-derivation.md?plain=1#L124

タイポ：`ボック化`→`ボックス化`

---

###  Realisation
macOSで実行してみたところ出力が記載されてるものと異なりました．
システムの`/bin/sh`を使ってるのが原因だと思うので対応は必要ないと思いますが一応報告です．

#### 再現手順
1. `drv.nix`を本文からコピペで作成．
2. `nix eval --file ./drv.nix`
3. `nix-store --realise /nix/store/l2wl0kf28qi3nqh53392a9f5vqp032m0-hello-txt.drv`
4. `cat /nix/store/xdb6bw1sjk8k0a6hsv5ijhdgm98dfwfh-hello-txt`

#### 期待される出力

```sh:
Hello
```

#### 実際の出力

```sh:
-n Hello
```

#### 備考

```sh:
/bin/bash -c "echo -n Hello"
Hello
```

bashだと問題ないのですが，version情報は`/bin/sh`も`/bin/bash`も同じなのが謎です．おま環説もありますが．．．

shellのversion
```sh:
/bin/sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

```sh:
/bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ultimatile** [comment]
本日分です🙇．
これでタイポチェックは最後まで行きました．これで一旦報告は終了します．
試せていないコマンドもあるのでそこで何かあればまた報告するかもしれません．
nix CLIのコマンドは意味もよくわからないまま叩いていたので勉強になりました．
まだ書き上がってない部分も楽しみにしております．

## Chapter 11 §1. Nix CLIの基本

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch02-01-nix-cli-basics.md?plain=1#L9
タイポ： `nixpkgs/nixpkgs`→`nixpkgs`

## Chapter 12 §2. Nixpkgsを使う

### 複数プラットフォームに対応する

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch02-02-use-nixpkgs.md?plain=1#L75
タイポ: `aaarch64-linux`→`aarch64-linux`

## Chapter 13 §3. devShellで開発環境構築

### 実行環境のバージョン管理

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch02-03-devshell.md?plain=1#L205
タイポ: 簡潔→完結

## Chapter 20 §1. helloのビルド

### 3. helloを作る

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch04-01-hello.md?plain=1#L83
タイポ: `hello.c`→`hello.rs`

---

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/ch04-01-hello.md?plain=1#L164
タイポ: `Patter`→`Pattern`

## Chapter 23 付録A. リンク集

### vim-jp slackのtech-nixチャンネル

https://github.com/asa1984/nix-zenn-articles/blob/82bf48c2b3fd143e883d85f0a6ec737e2abb9cb2/books/nix-hands-on/appendix-01-references.md?plain=1#L71
タイポ: `盛り上がりっています`→`盛り上がっています`

**Comment by asa1984** [comment]
## drv.nixについて
以下の補足を折り畳み要素で追加しておきます。
- `drv.nix`は説明を簡潔にするために誤魔化している部分があり、再現性がないこと
- ultimatileさんの環境と同じような結果になり得ること

**Comment by asa1984** [comment]
ultimatileさんのおかげでたくさんのタイポの修正と内容の改善を行うことができました。今回、実験的にプレビューを公開してみましたが、非常に有意義なものになりました。現在コミットしている範囲に関しては十分な修正を行うことができたと思うので、書きかけのセクションを追加し次第、Zennで公開する予定です。

ありがとうございます！

**Comment by hikuohiku** [comment]
@asa1984 
素晴らしい記事をありがとうございます！

一点間違いと思われる点がありましたのでこの場をお借りして報告させていただきます。

https://github.com/asa1984/nix-zenn-articles/blob/affa9450ce83ec0b728f97f1012acd012cdf12fd/books/nix-hands-on/ch01-01-nix-lang-basics.md?plain=1#L390-L395

`set: a + b` -> `set: set.a + set.b`
