### ISSUE TITLE
タイポの報告

### ISSUE THREAD

**Issue by whtsht** [asa1984/nix-zenn-articles#19]
こんにちは、記事のほう楽しく読ませてもらっています。

タイポにより`nix run`実行でエラーが出たのでご報告します。

https://github.com/asa1984/nix-zenn-articles/blob/5ec8fb080142bea6693b5f33bf59140c25b4a140/books/nix-hands-on/ch04-02-rust-project.md?plain=1#L127

callpackage → callPackage

**Comment by asa1984** [comment]
私事により確認が遅れました🙏
ご報告ありがとうございます！

**Comment by whtsht** [comment]
対応ありがとうございます！
